name: build-release

on:
  push:
    # branches:
      # - master
  pull_request:
    branches:
      - master


jobs:
  # lint

  # test

  build_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: build
      run: |
        GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=0.1.2" -o ssmps.exe main.go
        ssmps.exe
      shell: powershell

  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: build
      run: GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=0.1.2" -o ssmps main.go

  release:
      needs: build
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v1

      - name: release
        run: echo 'releasing'