name: build-release

on:
  push:
    # branches:
      # - master
  pull_request:
    branches:
      - master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: build
      run: ./build.sh

  release:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v1

      - name: release
        run: echo 'releasing'


