name: build-release

on:
  push: # all branches
  pull_request:
    branches:
      - master

jobs:
  # lint

  # test

  build_windows:
    runs-on: windows-latest

    env:
      GOOS: windows
      GOARCH: amd64

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        go build -ldflags "-X main.version=0.1.2" -o ssmps.exe main.go
      shell: powershell

    - name: Upload Windows build
      uses: actions/upload-artifact@v1
      with:
        name: windows-build
        path: ssmps.exe

  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=0.1.2" -o ssmps main.go

    - name: Upload Linux build
      uses: actions/upload-artifact@v1
      with:
        name: linux-build
        path: ssmps

  release:
      needs: [build_windows, build_linux]
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Download Windows build
        uses: actions/download-artifact@v1
        with:
          name: windows-build

      - name: Download Linux build
        uses: actions/download-artifact@v1
        with:
          name: linux-build

      - name: release
        run: ls -al
