name: build-release

on:
  push: # all branches
  pull_request:
    branches:
      - master

jobs:
  # lint

  # test

  build_windows:
    runs-on: windows-latest

    env:
      GOOS: windows
      GOARCH: amd64

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        go build -ldflags "-X main.version=0.1.2" -o ssmps.exe main.go
        ssmps.exe
      shell: powershell

  build_linux:
    runs-on: ubuntu-latest

    env:
      GOOS: linux

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=0.1.2" -o ssmps main.go

  release:
      needs: [build_windows, build_linux]
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: release
        run: echo 'releasing'
