name: build-release

on:
  push: # all branches
  pull_request:
    branches:
      - master

env:
  GOENV: amd64

jobs:
  # lint

  # test

  build_windows:
    runs-on: windows-latest

    env:
      GOPATH: ${{ runner.workspace }}
      GOOS: windows

    steps:
    - uses: actions/checkout@v1

    - name: build
      run: |
        echo ${env:GOOS} ${env:GOENV}
        go get
        go build -ldflags "-X main.version=0.1.2" -o ssmps.exe main.go
        ssmps.exe
      shell: powershell

  build_linux:
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ runner.workspace }}
      GOOS: linux

    steps:
    - uses: actions/checkout@v1

    - name: build
      run: |
        echo $GOOS echo $GOENV
        go get
        GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=0.1.2" -o ssmps main.go

  release:
      needs: [build_windows, build_linux]
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v1

      - name: release
        run: echo 'releasing'
