name: build-release

on:
  push: # all branches
  pull_request:
    branches:
      - master

jobs:
  # lint

  # test

  build_windows:
    runs-on: windows-latest

    env:
      GOOS: windows
      GOARCH: amd64

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        go build -ldflags "-X main.version=0.1.2" -o ssmps.exe main.go
      shell: powershell

    - name: Upload Windows build
      uses: actions/upload-artifact@v1
      with:
        name: ssmps.exe
        path: ssmps.exe

  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=0.1.2" -o ssmps main.go

    - name: Upload Linux build
      uses: actions/upload-artifact@v1
      with:
        name: ssmps
        path: ssmps

  release:
      needs: [build_windows, build_linux]
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Download Windows build
        uses: actions/download-artifact@v1
        with:
          name: ssmps.exe

      - name: Download Linux build
        uses: actions/download-artifact@v1
        with:
          name: ssmps

      # - name: release
      #   run: ls -al

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true

      - run: |
          zip ssmps.zip ssmps
          zip ssmps.exe.zip ssmps.exe
          ls -al

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`.
          # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./ssmps.exe.zip
          asset_name: ssmps.exe.zip
          asset_content_type: application/zip
          # application/vnd.microsoft.portable-executable